services:
  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-db-21-slim
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=Oracle2026
    volumes:
      - oracle-data:/opt/oracle-21/oradata
    healthcheck:
      test: ["CMD-SHELL", "sqlplus -s sys/Oracle2026@localhost:1521/XE as sysdba <<< 'SELECT 1 FROM DUAL;'"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  oracle-data:

#manually configure database name (run into db server)
#docker compose up -d (Start everything)
#docker compose ps (list all docker container)
#docker exec -it db_name_instance bash (to move inside postgres server)
#docker compose logs -f oracle-db -Check logs

#login to oracle
#docker exec -it oracle-db-21-slim bash -lc "sqlplus system@//localhost:1521/XEPDB1"
#docker exec -it oracle-db-21-slim sqlplus / as sysdba